In [14]:
import numpy as np
import pandas as pd
import seaborn as sns

titanic= sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [15]:
titanic.pivot_table('survived',index='sex',columns='class')

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [19]:
#qcut
fare=pd.qcut(titanic['fare'],2)
fare

0       (-0.001, 14.454]
1      (14.454, 512.329]
2       (-0.001, 14.454]
3      (14.454, 512.329]
4       (-0.001, 14.454]
             ...
886     (-0.001, 14.454]
887    (14.454, 512.329]
888    (14.454, 512.329]
889    (14.454, 512.329]
890     (-0.001, 14.454]
Name: fare, Length: 891, dtype: category
Categories (2, interval[float64, right]): [(-0.001, 14.454] < (14.454, 512.329]]

In [21]:
#cut
age=pd.cut(titanic['age'],[0,18,80])
titanic.pivot_table('survived',['sex','age'],'class')

class         First  Second  Third
sex    age
female 0.75     NaN     NaN   1.00
       1.00     NaN     NaN   1.00
       2.00     0.0     1.0   0.25
       3.00     NaN     1.0   0.00
       4.00     NaN     1.0   1.00
...             ...     ...    ...
male   70.00    0.0     0.0    NaN
       70.50    NaN     NaN   0.00
       71.00    0.0     NaN    NaN
       74.00    NaN     NaN   0.00
       80.00    1.0     NaN    NaN

[145 rows x 3 columns]

In [22]:
titanic.pivot_table('survived','sex',['class','alone'])

class      First              Second               Third
alone      False     True      False     True      False     True
sex
female  0.966667  0.970588  0.931818  0.906250  0.416667  0.616667
male    0.425532  0.333333  0.277778  0.097222  0.180723  0.121212

In [23]:
#margins
titanic.pivot_table('survived',index='sex',columns='class',margins=True)

class      First    Second     Third       All
sex
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

In [25]:
titanic.pivot_table(index='sex',columns='class',aggfunc={'survived':sum,'fare':'mean'})

              fare                       survived
class        First     Second      Third    First Second Third
sex
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

In [29]:
titanic.pivot_table(index='sex',columns='class',aggfunc={'age':'min','fare':'min'})

         age                  fare
class  First Second Third    First Second Third
sex
female  2.00   2.00  0.75  25.9292   10.5  6.75
male    0.92   0.67  0.42   0.0000    0.0  0.00

In [30]:
data = {
    "department": [
        "CSE",
        "AIML",
        "ECE",
        "CSE",
        "ECE",
        "AIML",
        "CSE",
        "ECE",
        "AIML",
        "CSE",
        "AIML",
        "ECE",
    ],
    "gender": ["M", "F", "F", "F", "M", "M", "M", "F", "M", "F", "M", "M"],
    "salary": [
        85000,
        92000,
        78000,
        90000,
        76000,
        95000,
        82000,
        80000,
        88000,
        91000,
        97000,
        75000,
    ],
}

df = pd.DataFrame(data)
print(df)

   department gender  salary
0         CSE      M   85000
1        AIML      F   92000
2         ECE      F   78000
3         CSE      F   90000
4         ECE      M   76000
5        AIML      M   95000
6         CSE      M   82000
7         ECE      F   80000
8        AIML      M   88000
9         CSE      F   91000
10       AIML      M   97000
11        ECE      M   75000

In [41]:
pivot_salary = df.pivot_table(
    values="salary", index="gender", columns="department",
)
print(pivot_salary)

department          AIML      CSE      ECE
gender
F           92000.000000  90500.0  79000.0
M           93333.333333  83500.0  75500.0

In [42]:
pivot_salary = df.pivot_table(
    values="salary", index="gender", columns="department",
)